package(default_visibility = ["//visibility:public"])

licenses(["notice"])
exports_files(["COPYING"])

cc_library(name = 'snappy',
     srcs = [
        'snappy.cc',
        'snappy-c.cc',
        'snappy-sinksource.cc',
        'snappy-stubs-internal.cc'
    ],
    hdrs = [
        'snappy.h',
        'snappy-c.h',
        'snappy-sinksource.h',
        'snappy-stubs-public.h',
        'snappy-internal.h',
        'snappy-stubs-internal.h',
    ],
)
